# Generated by Django 5.0.4 on 2024-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_albummodel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='rating',
            field=models.CharField(help_text='please submit a rating between 1 to 5', max_length=1),
        ),
    ]
